#!/usr/bin/env python3
"""
Batch generate static ad images from a JSON prompts file using Nano Banana 2 (Gemini).

Reads a prompts.json file (generated by ads-designer batch mode), fires each prompt
to Gemini's image generation API, and saves results to organized folders. Templates
tagged with needs_product_images get your real product photos passed as reference
images so the model matches your actual packaging.

Usage:
    # Full batch run with product images
    python generate_ads.py --prompts prompts.json --product-images front.png angle.png

    # Specific templates only
    python generate_ads.py --prompts prompts.json --templates 1,7,15,21

    # Text-only (no product images)
    python generate_ads.py --prompts prompts.json

    # Custom output directory and variations
    python generate_ads.py --prompts prompts.json --output ./my-ads/ --count 3
"""

import argparse
import base64
import io
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from PIL import Image
from google import genai
from google.genai import types

load_dotenv()

# Nano Banana 2 via Gemini API
MODEL = "gemini-3-pro-image-preview"
API_KEY = os.getenv("NANO_BANANA_API_KEY") or os.getenv("GEMINI_API_KEY")

# Max dimensions for product reference images (keep them reasonable for API)
REF_MAX_SIZE = (800, 800)


def load_product_image(path: Path) -> Image.Image | None:
    """Load and resize a product reference image."""
    try:
        img = Image.open(path)
        if img.mode not in ("RGB", "RGBA"):
            img = img.convert("RGB")
        img.thumbnail(REF_MAX_SIZE, Image.Resampling.LANCZOS)
        return img
    except Exception as e:
        print(f"  Warning: Could not load {path}: {e}")
        return None


def load_product_images(paths: list[str]) -> list[Image.Image]:
    """Load all product reference images from the given paths."""
    images = []
    for p in paths:
        path = Path(p)
        if path.is_dir():
            # Load all images from directory
            for ext in ("*.png", "*.jpg", "*.jpeg", "*.webp"):
                for img_path in sorted(path.glob(ext)):
                    img = load_product_image(img_path)
                    if img:
                        images.append(img)
                        print(f"  Loaded: {img_path.name} ({img.size[0]}x{img.size[1]})")
        elif path.is_file():
            img = load_product_image(path)
            if img:
                images.append(img)
                print(f"  Loaded: {path.name} ({img.size[0]}x{img.size[1]})")
        else:
            print(f"  Warning: {p} not found, skipping")

    return images


def generate_ad(
    prompt_text: str,
    product_images: list[Image.Image] | None = None,
    needs_product_images: bool = False,
) -> Image.Image | None:
    """
    Generate a single ad image via Gemini API.

    If needs_product_images is True and product_images are provided,
    they're passed as reference images in the contents array so the
    model can match real product packaging.
    """
    client = genai.Client(api_key=API_KEY)

    # Build contents: product images first (as reference), then the prompt
    if needs_product_images and product_images:
        num_refs = len(product_images)
        ref_label = f"IMAGE{'S' if num_refs > 1 else ''} 1{f'-{num_refs}' if num_refs > 1 else ''}: Reference photo{'s' if num_refs > 1 else ''} of the actual product packaging. Match this product exactly in the output.\n\n"
        full_prompt = ref_label + prompt_text
        contents = list(product_images) + [full_prompt]
    else:
        contents = [prompt_text]

    try:
        response = client.models.generate_content(
            model=MODEL,
            contents=contents,
            config=types.GenerateContentConfig(
                response_modalities=["TEXT", "IMAGE"],
            ),
        )

        # Extract generated image from response
        if response.candidates and response.candidates[0].content:
            for part in response.candidates[0].content.parts:
                if hasattr(part, "inline_data") and part.inline_data:
                    data = part.inline_data.data
                    if data:
                        img_bytes = (
                            base64.b64decode(data)
                            if isinstance(data, str)
                            else data
                        )
                        return Image.open(io.BytesIO(img_bytes))
                elif hasattr(part, "text") and part.text:
                    print(f"    Model note: {part.text[:150]}")

        print("    No image in response")
        return None

    except Exception as e:
        print(f"    Error: {e}")
        return None


def sanitize_name(name: str) -> str:
    """Convert template name to filesystem-safe directory name."""
    return re.sub(r"[^a-z0-9_-]", "", name.lower().replace(" ", "_").replace("/", "_"))


def run_batch(
    prompts_path: str,
    product_image_paths: list[str] | None = None,
    output_dir: str | None = None,
    count: int = 1,
    delay: float = 3.0,
    template_filter: list[int] | None = None,
):
    """Run the full batch generation pipeline."""

    # Load prompts
    prompts_file = Path(prompts_path)
    if not prompts_file.exists():
        print(f"Error: Prompts file not found: {prompts_path}")
        sys.exit(1)

    with open(prompts_file) as f:
        data = json.load(f)

    prompts = data.get("prompts", [])
    brand = data.get("brand", "unknown")
    product = data.get("product", "")

    if not prompts:
        print("Error: No prompts found in file")
        sys.exit(1)

    # Filter templates if specified
    if template_filter:
        prompts = [p for p in prompts if p["template_number"] in template_filter]
        if not prompts:
            print(f"Error: No matching templates for filter: {template_filter}")
            sys.exit(1)

    # Set up output directory
    if output_dir:
        out_path = Path(output_dir)
    else:
        out_path = prompts_file.parent / "output"
    out_path.mkdir(parents=True, exist_ok=True)

    # Load product images
    product_images = []
    if product_image_paths:
        print(f"\nLoading product images...")
        product_images = load_product_images(product_image_paths)
        if not product_images:
            print("Warning: No product images loaded. Generating without references.")

    # Summary
    print(f"\n{'='*60}")
    print(f"  Brand: {brand}")
    if product:
        print(f"  Product: {product}")
    print(f"  Templates: {len(prompts)}")
    print(f"  Variations per template: {count}")
    print(f"  Total images to generate: {len(prompts) * count}")
    print(f"  Product images loaded: {len(product_images)}")
    print(f"  Output: {out_path}")
    print(f"  Delay between calls: {delay}s")
    print(f"{'='*60}\n")

    # Track results
    results = {
        "brand": brand,
        "product": product,
        "started_at": datetime.now().isoformat(),
        "total_prompts": len(prompts),
        "variations_per_prompt": count,
        "product_images_used": len(product_images),
        "results": [],
    }

    total = len(prompts) * count
    completed = 0
    failed = 0

    for prompt_data in prompts:
        num = prompt_data["template_number"]
        name = prompt_data.get("template_name", f"template_{num}")
        needs_product = prompt_data.get("needs_product_images", False)
        prompt_text = prompt_data["prompt"]

        # Create template output directory
        dir_name = f"{num:02d}_{sanitize_name(name)}"
        template_dir = out_path / dir_name
        template_dir.mkdir(parents=True, exist_ok=True)

        # Save prompt text for reference
        (template_dir / "prompt.txt").write_text(prompt_text, encoding="utf-8")

        print(f"[{num:02d}] {name}")
        print(f"     Product ref: {'Yes' if needs_product and product_images else 'No'}")

        for v in range(count):
            completed += 1
            label = f"v{v + 1}" if count > 1 else "v1"
            print(f"     Generating {label} ({completed}/{total})...", end=" ", flush=True)

            result = generate_ad(
                prompt_text=prompt_text,
                product_images=product_images if needs_product else None,
                needs_product_images=needs_product,
            )

            if result:
                img_path = template_dir / f"ad_{label}.png"
                result.save(img_path, "PNG")
                print(f"Saved ({result.size[0]}x{result.size[1]})")
                results["results"].append({
                    "template_number": num,
                    "template_name": name,
                    "variation": label,
                    "status": "success",
                    "file": str(img_path.relative_to(out_path)),
                    "size": f"{result.size[0]}x{result.size[1]}",
                })
            else:
                # Retry once
                print("Failed, retrying...", end=" ", flush=True)
                time.sleep(delay)
                result = generate_ad(
                    prompt_text=prompt_text,
                    product_images=product_images if needs_product else None,
                    needs_product_images=needs_product,
                )
                if result:
                    img_path = template_dir / f"ad_{label}.png"
                    result.save(img_path, "PNG")
                    print(f"Saved on retry ({result.size[0]}x{result.size[1]})")
                    results["results"].append({
                        "template_number": num,
                        "template_name": name,
                        "variation": label,
                        "status": "success_retry",
                        "file": str(img_path.relative_to(out_path)),
                        "size": f"{result.size[0]}x{result.size[1]}",
                    })
                else:
                    print("Failed")
                    failed += 1
                    results["results"].append({
                        "template_number": num,
                        "template_name": name,
                        "variation": label,
                        "status": "failed",
                    })

            # Rate limit delay
            if completed < total:
                time.sleep(delay)

    # Save results summary
    results["completed_at"] = datetime.now().isoformat()
    results["succeeded"] = completed - failed
    results["failed"] = failed

    results_path = out_path / "results.json"
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2)

    # Print summary
    print(f"\n{'='*60}")
    print(f"  Done! {completed - failed}/{completed} images generated")
    if failed:
        print(f"  Failed: {failed}")
    print(f"  Results: {results_path}")
    print(f"  Output: {out_path}")
    print(f"{'='*60}")

    # Auto-generate gallery
    gallery_script = Path(__file__).parent / "generate_gallery.py"
    if gallery_script.exists():
        print(f"\nGenerating HTML gallery...")
        subprocess.run([sys.executable, str(gallery_script), "--input", str(out_path)])
    else:
        print(f"\nTip: Run generate_gallery.py --input \"{out_path}\" to create an HTML gallery")

    return results


def main():
    parser = argparse.ArgumentParser(
        description="Batch generate static ad images using Nano Banana 2 (Gemini)"
    )
    parser.add_argument(
        "--prompts", "-p",
        required=True,
        help="Path to the JSON prompts file (from ads-designer batch mode)",
    )
    parser.add_argument(
        "--product-images", "-i",
        nargs="*",
        help="Product image files or directories. Images are passed as reference for templates that need them.",
    )
    parser.add_argument(
        "--output", "-o",
        help="Output directory (default: ./output/ next to prompts file)",
    )
    parser.add_argument(
        "--count", "-n",
        type=int,
        default=1,
        help="Number of variations per template (default: 1)",
    )
    parser.add_argument(
        "--delay", "-d",
        type=float,
        default=3.0,
        help="Delay in seconds between API calls (default: 3.0)",
    )
    parser.add_argument(
        "--templates", "-t",
        help="Comma-separated template numbers to generate (e.g., 1,7,15,21)",
    )

    args = parser.parse_args()

    if not API_KEY:
        print("Error: Set NANO_BANANA_API_KEY or GEMINI_API_KEY environment variable")
        sys.exit(1)

    template_filter = None
    if args.templates:
        template_filter = [int(t.strip()) for t in args.templates.split(",")]

    run_batch(
        prompts_path=args.prompts,
        product_image_paths=args.product_images,
        output_dir=args.output,
        count=args.count,
        delay=args.delay,
        template_filter=template_filter,
    )


if __name__ == "__main__":
    main()
